server.port=8081
spring.datasource.url=jdbc:h2:file:../recipe-api/data/recipe-db;AUTO_SERVER=TRUE
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=none

file.upload-dir=../recipe-api/uploads
worker.poll-interval-ms=5000
